[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
    'npm install -g pnpm@10.4.1',
    'pnpm install --frozen-lockfile --filter=api...'
]

[phases.build]
cmds = [
    'pnpm --filter=@workspace/db db:generate',
    'pnpm --filter=api build'
]

[start]
cmd = 'pnpm --filter=api start'
