[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
    'corepack enable',
    'corepack prepare pnpm@10.4.1 --activate',
    'cd ../.. && pnpm install --frozen-lockfile --filter=api...'
]

[phases.build]
cmds = [
    'cd ../.. && pnpm --filter=@workspace/db db:generate',
    'cd ../.. && pnpm --filter=api build'
]

[start]
cmd = 'cd ../.. && pnpm --filter=api start'
